apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tag: latest
    app: techtrends
  name: techtrends-deployment
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: ksaleh/techtrends:latest
        ports:
         - containerPort: 3111
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111

