apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends-svc
  namespace: sandbox
spec:
  ports:
  - port: {{.Values.service.port}}  #4111 external port
    protocol: {{.Values.service.protocol}} #TCP
    targetPort: {{.Values.service.targetPort}} #3111  internal port
  selector:
    app: techtrends
    tag: latest
  type: {{.Values.service.type}}
