apiVersion: v1
kind: Service
metadata:
  annotations:

  labels:
    app: techtrends
    tag: latest
  name: techtrends-svc
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  #- port: {{.Values.service.port}}  #4111 external port
  -
    name: http
    port: {{.Values.service.protocol}}
    protocol: {{.Values.service.protocol}} #TCP
    targetPort: {{.Values.service.targetPort}} #3111  internal port
    nodePort: 30020


  selector:
    app: techtrends
    tag: latest

  type: {{.Values.service.type}}

status:
  loadBalancer: {}