#Github workflow to build and package techtrends project to docker hub
name: "TechTrends - Package with Docker"

#Set th event where the jobs will be triggered when it happens
on:
  push:
    branches: [main]


#start the followings jobs    
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:project"
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ksaleh/techtrends:latest
